import Head from 'next/head'
import NotPlaying from '../components/NotPlaying'
import CurrentlyPlaying from '../components/CurrentlyPlaying'
import Link from 'next/link'
export default function Home({ currentlyPlayingData }) {
  return (
    <div>
      <Head>
        <title>{`Currently Playing - ${currentlyPlayingData.songName}`}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/spotify.svg' />
      </Head>

      <main className='flex flex-col justify-center items-center h-screen bg-gray-100'>
        <h1 className='text-center text-2xl sm:text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-green-500 py-4'>
          What is Kevin listening to? Using ISR
        </h1>
        <Link href='/swr'>
          <a>Go to swr</a>
        </Link>
        {currentlyPlayingData ? (
          <CurrentlyPlaying currentlyPlayingData={currentlyPlayingData} />
        ) : (
          <NotPlaying />
        )}
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch('http://localhost:3000/api/current_song')
  const data = await res.json()
  console.log(data)
  if (!data.isPlaying) {
    return {
      props: {
        currentlyPlayingData: false,
      },
      revalidate: 5,
    }
  } else {
    const {
      name: songName,
      artists: artistsData,
      album: { images },
    } = data.data.item
    const img = images[2].url
    const artists = artistsData.map(artist => artist.name).join(', ')
    return {
      props: {
        currentlyPlayingData: { songName, artists, img },
      },
      revalidate: 5,
    }
  }
}
